name: Security

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  security-events: write
  actions: read

jobs:

  # ==========================================
  # 1 - Dependências
  # ==========================================
  dependency-scan:
    name: Dependency Security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Auditoria NPM
        run: npm audit --audit-level=high


  # ==========================================
  # 2 - CodeQL
  # ==========================================
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript-typescript
          queries: security-extended

      - name: Analisar
        uses: github/codeql-action/analyze@v4


  # ==========================================
  # 3 - Build
  # ==========================================
  build:
    name: Build Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Build Next.js
        run: npm run build
